language: java
jdk:
  - oraclejdk8
script:
  - mvn -B clean package -Djavax.xml.accessExternalSchema=all
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - '$HOME/.m2/repository'
